### ISSUE TITLE
程序输入密码 后立即关闭程序

### ISSUE THREAD

**Issue by whitecat332** [windoyy/-#1]
双击签到.exe，后输入用户名，显示从配置文件中获取密码，然后立即显示账号或密码错误，可根本没有让我输入密码，然后程序关闭！

**Comment by windoyy** [comment]
超星更换了api 新增了签名验证 程序对请求失败没有做提示信息所以直接退出了
鉴于github上有其他非常优秀的类似项目 本项目不再更新
